from utils import get_max_dimension
import pygame
import math

CURRENT_MAX_DIMENSION = get_max_dimension()
TILE_WIDTH = 16
TILE_HEIGHT = 16
VIEW_PORT_TILES_W = 32
VIEW_PORT_TILES_H = 32
pygame.init()
SCALE_FACTOR = math.ceil(CURRENT_MAX_DIMENSION / TILE_WIDTH / VIEW_PORT_TILES_W)
TILES = 100
MAP_WIDTH = TILE_WIDTH * TILES
MAP_HEIGHT = TILE_HEIGHT * TILES
SCREEN_WIDTH = CURRENT_MAX_DIMENSION - 1 / 6 * CURRENT_MAX_DIMENSION
SCREEN_HEIGHT = CURRENT_MAX_DIMENSION - 1 / 6 * CURRENT_MAX_DIMENSION
