from settings import CURRENT_MAX_DIMENSION
from spritesheet.utils import get_animation_matrix

PLAYER_ANIMATION_MATRIX = get_animation_matrix("player_movement")
MAIN_PLAYER_NAME = "Kuncho"
MAIN_PLAYER_X_POS = CURRENT_MAX_DIMENSION / 2
MAIN_PLAYER_Y_POS = CURRENT_MAX_DIMENSION / 2
MAIN_PLAYER_HEALTH_POINTS = 100
MAIN_PLAYER_DAMAGE_POINTS = 20
MAIN_PLAYER_CURRENT_ANIMATION_FRAME = PLAYER_ANIMATION_MATRIX[0]
MAIN_PLAYER_ANIMATION_FRAMES = PLAYER_ANIMATION_MATRIX
