from settings import CURRENT_MAX_DIMENSION

MAIN_PLAYER_NAME = "Kuncho"
MAIN_PLAYER_X_POS = CURRENT_MAX_DIMENSION / 2
MAIN_PLAYER_Y_POS = CURRENT_MAX_DIMENSION / 2
MAIN_PLAYER_HEALTH_POINTS = 100
MAIN_PLAYER_DAMAGE_POINTS = 20
MAIN_PLAYER_CURRENT_ANIMATION_FRAME = None
MAIN_PLAYER_ANIMATION_FRAMES = None
