MAIN_PLAYER_NAME = "Kuncho"
MAIN_PLAYER_X_POS = 700
MAIN_PLAYER_Y_POS = 500
MAIN_PLAYER_HEALTH_POINTS = 100
MAIN_PLAYER_DAMAGE_POINTS = 20
ARROW_DAMAGE_FOR_ENEMY = 20
ARROW_DAMAGE_FOR_PLAYER = 30

